import { SHAPES, LEVEL_SIGNATURES, STREET_KIT_ASSETS, SCENE_PROFILES, URBAN_KIT, solidBoxes, topFaces, triggerBoxes, clamp } from './config.js?v=10';
import { LEVELS, makeRoute, PLATFORM_RULES } from './routes.js?v=11';
import { BUILDER_CATALOG, BUILDER_BY_ID, BUILDER_COUNT } from './builder-catalog.js?v=8';
import { loadRuntimeManifest } from './load-manifest.js?v=12';
import { BACKGROUND_ALPHA, BACKGROUND_LANE_CLEARANCE, BACKGROUND_PARALLAX, backgroundPlateFor, backgroundPlacementFor } from './depth.js?v=3';

const $=id=>document.getElementById(id);
const canvas=$('editorCanvas'),ctx=canvas.getContext('2d'),preview=$('previewCanvas'),previewCtx=preview.getContext('2d');
const STORE='sneakers-run-editor-v1';
const PICKUPS={coin:{name:'coin pickup',art:'coin',width:38,height:38},shield:{name:'shield pickup',art:'shield',width:52,height:52},magnet:{name:'magnet pickup',art:'magnet',width:52,height:52},speed:{name:'rush pickup',art:'speed',width:52,height:52}};
const GROUPS=[['STRUCTURES',['platform','fireEscape','conveyor','shutter','crane','train','securityGate']],['OBSTACLES',['barrier','car','barrel','gate','bollards','sweeper','truck','spikes','electric']],['STREET KIT',STREET_KIT_ASSETS],['GOALS & SWITCHES',['checkpoint','finish','button']],['LEVEL SIGNATURES',LEVEL_SIGNATURES],['ENEMIES',Object.keys(SHAPES).filter(key=>SHAPES[key].enemy)],['PICKUPS',Object.keys(PICKUPS)]];
const state={name:'Untitled route',stage:0,sceneStage:0,entities:[],pickups:[],length:3200,selected:null,zoom:.5,scroll:0,grid:25,showBoxes:false,drag:null,history:[],future:[],dirty:false};
let atlas,kit,manifest,scene,sceneToken=0,uid=0,renderQueued=false,paletteDrag=null,lastPointer={x:0,y:0};
const isPickup=item=>item&&item.kind==='pickup';
const collection=item=>isPickup(item)?state.pickups:state.entities;
const catalogShape=type=>{const entry=BUILDER_BY_ID[type];if(!entry)return null;const base=entry.kind==='pickup'?PICKUPS[entry.base]:SHAPES[entry.base];return base?{...base,name:entry.name,assetId:type,behavior:entry.behavior,profile:entry.profile,base:entry.base,playground:true}:null;};
const shapeFor=item=>isPickup(item)?PICKUPS[item.type]||catalogShape(item.type):SHAPES[item.type]||catalogShape(item.type);
const shapeForType=type=>PICKUPS[type]||SHAPES[type]||catalogShape(type);
const entryFor=item=>BUILDER_BY_ID[item.type];
const selected=()=>[...state.entities,...state.pickups].find(item=>item.id===state.selected)||null;
function frameIndexFor(item,shape=shapeFor(item)){
 const count=manifest?.sprites[shape?.art]?.length||1;
 return shape?.loop?Math.floor(performance.now()/(1000/(shape.fps||4)))%count:item.type==='coin'||entryFor(item)?.base==='coin'?2:0;
}
const frameFor=(item,shape=shapeFor(item),index=frameIndexFor(item,shape))=>manifest?.sprites[shape?.art]?.[index];
const sceneProfile=()=>SCENE_PROFILES[LEVELS[state.sceneStage]?.scene];
function plateFor(m){const imageWidth=scene?.naturalWidth||scene?.width||16,imageHeight=scene?.naturalHeight||scene?.height||9;return backgroundPlateFor(m.width,m.height,m.ground,imageWidth/imageHeight,m.scale,sceneProfile());}
function backgroundPlacement(item,shape=shapeFor(item),frame=manifest?.sprites[shape?.art]?.[0],worldHeight=Infinity,laneClearance=BACKGROUND_LANE_CLEARANCE){
 const background=backgroundItem(item);
 if(!background)return{background:false,track:0,factor:1,elevation:item.y||0,alpha:1};
 const placement=backgroundPlacementFor(item,shape,frame,worldHeight,laneClearance);
 return{background:true,...placement,alpha:BACKGROUND_ALPHA};
}
const backgroundVisualLift=(item,shape=shapeFor(item),frame=manifest?.sprites[shape?.art]?.[0],worldHeight=Infinity,laneClearance=BACKGROUND_LANE_CLEARANCE)=>backgroundPlacement(item,shape,frame,worldHeight,laneClearance).elevation-(item.y||0);
function renderedBounds(item,shape,placement,frame=frameFor(item,shape)){
 const pickup=isPickup(item)||entryFor(item)?.kind==='pickup',factor=placement.factor;
 const width=frame?.width||shape.width,height=frame?.height||shape.height;
 const pivotX=frame?.pivotX??width/2,pivotY=frame?.pivotY??height;
 const anchorX=pickup?item.x:item.x+shape.width/2,anchorY=placement.background?placement.elevation:(item.y||0);
 return{left:anchorX-pivotX*factor,right:anchorX+(width-pivotX)*factor,bottom:anchorY-(height-pivotY)*factor,top:anchorY+pivotY*factor,anchorX,anchorY,factor};
}
const serialise=()=>({version:1,name:state.name,stage:state.stage,backgroundStage:state.sceneStage,length:state.length,entities:state.entities.map(cleanEntity),pickups:state.pickups.map(cleanPickup)});
function cleanEntity(e){const sh=shapeForType(e.type);if(!sh)return null;const out={id:e.id,type:e.type,x:Math.round(e.x),y:Math.round(e.y||0),width:sh.width,height:sh.height,hit:false,passed:false};if(e.decorative||sh.decorative)out.decorative=true;if(e.background||e.decorative||sh.decorative)out.background=true;if(e.backgroundGroup)out.backgroundGroup=e.backgroundGroup;if(Number.isInteger(e.backgroundTrack))out.backgroundTrack=e.backgroundTrack;if(e.backgroundLift!==undefined)out.backgroundLift=e.backgroundLift;if(e.flybySpeed!==undefined)out.flybySpeed=e.flybySpeed;if(e.flybyFrequency!==undefined)out.flybyFrequency=e.flybyFrequency;if(e.patrol)out.patrol={min:Math.round(e.patrol.min),max:Math.round(e.patrol.max),speed:Math.round(e.patrol.speed)},out.direction=e.direction||-1;if(typeof e.floorPhase==='boolean')out.floorPhase=e.floorPhase;if(Number.isFinite(e.phaseOffset))out.phaseOffset=e.phaseOffset;return out;}
function cleanPickup(p){return{id:p.id,type:p.type,x:Math.round(p.x),y:Math.round(p.y),kind:'pickup'};}
function snapshot(){return JSON.stringify(serialise());}
function checkpoint(){state.history.push(snapshot());if(state.history.length>80)state.history.shift();state.future=[];state.dirty=true;updateHistory();}
function restore(raw){const data=typeof raw==='string'?JSON.parse(raw):raw;state.name=String(data.name||'Untitled route').slice(0,80);state.stage=clamp(Number(data.stage)||0,0,LEVELS.length-1);state.sceneStage=clamp(Number(data.backgroundStage??data.sceneStage??state.stage)||0,0,LEVELS.length-1);state.entities=Array.isArray(data.entities)?data.entities.filter(e=>{const entry=BUILDER_BY_ID[e.type];return shapeForType(e.type)&&entry?.kind!=='pickup'}).map(e=>({...cleanEntity(e),id:e.id||idFor(e.type)})).filter(Boolean):[];state.pickups=Array.isArray(data.pickups)?data.pickups.filter(p=>PICKUPS[p.type]||BUILDER_BY_ID[p.type]?.kind==='pickup').map(p=>({...cleanPickup(p),id:p.id||idFor(p.type)})):[];state.length=Math.max(1200,Number(data.length)||extent()+500);state.selected=null;state.dirty=false;$('routeName').value=state.name;$('stageSelect').value=state.stage;$('sceneSelect').value=state.sceneStage;loadScene();sync();}
function undo(){if(!state.history.length)return;state.future.push(snapshot());restore(state.history.pop());updateHistory();status('Undid last change');}
function redo(){if(!state.future.length)return;state.history.push(snapshot());restore(state.future.pop());updateHistory();status('Redid change');}
function updateHistory(){$('undoButton').disabled=!state.history.length;$('redoButton').disabled=!state.future.length;}
function idFor(type){return`edit:${type}:${Date.now().toString(36)}:${++uid}`;}
function extent(){return Math.max(0,...state.entities.map(e=>{const sh=shapeForType(e.type);return sh?e.x+sh.width:0}),...state.pickups.map(p=>{const sh=shapeForType(p.type);return sh?p.x+sh.width/2:0}));}
function snap(value){return state.grid===1?Math.round(value):Math.round(value/state.grid)*state.grid;}
function normalizeLength(){state.length=Math.max(1200,Math.ceil((extent()+500)/100)*100);}
function add(type,kind,x,y){const sh=shapeForType(type);if(!sh)return null;checkpoint();const item=kind==='pickup'?{id:idFor(type),kind:'pickup',type,x:snap(x),y:Math.max(25,snap(y))}:{id:idFor(type),type,x:snap(x),y:Math.max(0,snap(y)),width:sh.width,hit:false,passed:false,...(sh.decorative?{decorative:true,background:true}:{})};collection(item).push(item);state.selected=item.id;normalizeLength();sync();status(`Added ${shapeFor(item).name}`);return item;}
function removeSelected(){const item=selected();if(!item)return;checkpoint();const list=collection(item),index=list.indexOf(item);list.splice(index,1);state.selected=null;normalizeLength();sync();status(`Deleted ${shapeFor(item).name}`);}
function duplicateSelected(){const item=selected();if(!item)return;checkpoint();const copy={...structuredClone(item),id:idFor(item.type),x:snap(item.x+75)};if(copy.patrol){const delta=copy.x-item.x;copy.patrol.min+=delta;copy.patrol.max+=delta;}collection(item).push(copy);state.selected=copy.id;normalizeLength();sync();status(`Duplicated ${shapeFor(item).name}`);}

async function loadImage(url){const image=new Image();image.src=url;await image.decode();return image;}
async function loadAssets(){manifest=await loadRuntimeManifest();const cacheKey=manifest.atlasHash?`?v=${manifest.atlasHash.slice(0,16)}`:'';atlas=await loadImage(`assets/runtime/${manifest.image}${cacheKey}`);kit=await loadImage(URBAN_KIT.image);await loadScene();}
async function loadScene(){const stage=state.sceneStage,token=++sceneToken,file=LEVELS[stage].scene.replace('.png','.webp');try{const image=await loadImage(`assets/runtime/${file}`);if(token!==sceneToken||stage!==state.sceneStage)return;scene=image;draw();}catch{if(token===sceneToken)status('Background scenery could not be loaded');}}
function sprite(target,name,index,x,y,scale=1,alpha=1){const frames=manifest?.sprites[name];if(!frames)return;const f=frames[Math.min(index,frames.length-1)],s=scale;target.save();target.globalAlpha=alpha;target.drawImage(atlas,...f.rect,x-f.pivotX*s,y-f.pivotY*s,f.width*s,f.height*s);target.restore();}
function kitSprite(target,name,x,y,scale=1,alpha=1,offsetY=0){const source=URBAN_KIT[name];if(!source||!kit)return;const [sx,sy,sw,sh]=source,s=scale,anchorY=y-offsetY*s;target.save();target.globalAlpha=alpha;target.drawImage(kit,sx,sy,sw,sh,x-sw*s/2,anchorY-sh*s,sw*s,sh*s);target.restore();}
function supportColumn(x,height,m){if(!height||!manifest?.sprites.support?.[0])return;const f=manifest.sprites.support[0],[sx,sy,sw,sh]=f.rect,module=f.height;for(let cursor=0;cursor<height;cursor+=module){const visible=Math.min(module,height-cursor),anchorY=m.y(cursor),topY=m.y(cursor+visible);ctx.save();ctx.beginPath();ctx.rect(m.x(x-f.width/2),topY,f.width*m.scale,Math.max(1,anchorY-topY));ctx.clip();ctx.drawImage(atlas,sx,sy,sw,sh,m.x(x-f.pivotX),anchorY-f.pivotY*m.scale,f.width*m.scale,f.height*m.scale);ctx.restore();}}

function resize(){const box=canvas.getBoundingClientRect(),ratio=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(box.width*ratio));canvas.height=Math.max(1,Math.round(box.height*ratio));ctx.setTransform(ratio,0,0,ratio,0,0);draw();}
function metrics(){const box=canvas.getBoundingClientRect(),ground=box.height-56;return{width:box.width,height:box.height,ground,scale:state.zoom,x:value=>(value-state.scroll)*state.zoom,y:value=>ground-value*state.zoom};}
function drawGrid(m){const step=state.grid===1?100:state.grid,px=step*m.scale;if(px<8)return;ctx.save();ctx.strokeStyle='rgba(23,35,41,.13)';ctx.lineWidth=1;ctx.beginPath();let start=Math.floor(state.scroll/step)*step;for(let x=start;x<state.scroll+m.width/m.scale+step;x+=step){const sx=m.x(x);ctx.moveTo(sx,0);ctx.lineTo(sx,m.height);}for(let y=0;y<650;y+=step){const sy=m.y(y);ctx.moveTo(0,sy);ctx.lineTo(m.width,sy);}ctx.stroke();ctx.restore();}
function drawBackground(m){ctx.fillStyle='#91c9e8';ctx.fillRect(0,0,m.width,m.height);const plate=plateFor(m);if(!scene)return plate;const travel=((state.scroll*m.scale*BACKGROUND_PARALLAX)%plate.width+plate.width)%plate.width;for(let plateX=-travel;plateX<m.width;plateX+=plate.width)ctx.drawImage(scene,0,0,scene.width,scene.height,plateX,plate.top,plate.width+.5,plate.height);ctx.fillStyle='rgba(247,241,222,.13)';ctx.fillRect(0,0,m.width,m.height);return plate;}
function baseCollisionItem(item){const entry=entryFor(item);return entry?{...item,type:entry.base}:item;}
function drawItem(item,m,selectedItem=false,laneClearance=BACKGROUND_LANE_CLEARANCE){const sh=shapeFor(item);if(!sh)return;const frame=frameIndexFor(item,sh),sourceFrame=frameFor(item,sh,frame),placement=backgroundPlacement(item,sh,sourceFrame,m.ground/m.scale,laneClearance),bounds=renderedBounds(item,sh,placement,sourceFrame),x=m.x(bounds.anchorX),y=m.y(bounds.anchorY),factor=m.scale*bounds.factor,pickup=isPickup(item)||entryFor(item)?.kind==='pickup';ctx.save();if(placement.background){ctx.filter='brightness(1.13) saturate(.84)';ctx.globalAlpha=placement.alpha;}if(selectedItem){ctx.shadowColor='#f7c844';ctx.shadowBlur=14;}if(sh.special)kitSprite(ctx,sh.special,x,y,factor,placement.alpha,sh.artOffsetY||0);else sprite(ctx,sh.art,frame,x,y,factor,placement.alpha);ctx.restore();if(selectedItem){ctx.save();ctx.strokeStyle='#f7c844';ctx.lineWidth=2;ctx.setLineDash([6,4]);ctx.strokeRect(m.x(bounds.left)-3,m.y(bounds.top)-3,(bounds.right-bounds.left)*m.scale+6,(bounds.top-bounds.bottom)*m.scale+6);ctx.restore();}if(state.showBoxes){ctx.save();ctx.lineWidth=1.5;if(pickup){const box={x:item.x-17,y:item.y-17,w:34,h:34};ctx.strokeStyle='#145fff';ctx.strokeRect(m.x(box.x),m.y(box.y+box.h),box.w*factor,box.h*factor);}else{const base=baseCollisionItem(item);ctx.strokeStyle='#ed3d5b';for(const b of solidBoxes(base)){ctx.strokeRect(m.x(b.x),m.y(b.y+b.h),b.w*factor,b.h*factor);}ctx.strokeStyle='#0b875b';for(const f of topFaces(base)){ctx.beginPath();ctx.moveTo(m.x(f.x),m.y(f.y));ctx.lineTo(m.x(f.x+f.w),m.y(f.y));ctx.stroke();}ctx.strokeStyle='#9b6cff';for(const b of triggerBoxes(base)){ctx.setLineDash([5,3]);ctx.strokeRect(m.x(b.x),m.y(b.y+b.h),b.w*factor,b.h*factor);ctx.setLineDash([]);}}ctx.restore();}if(item.patrol){ctx.save();ctx.strokeStyle='#fff2a8';ctx.setLineDash([4,3]);ctx.beginPath();ctx.moveTo(m.x(item.patrol.min),m.y(18));ctx.lineTo(m.x(item.patrol.max),m.y(18));ctx.stroke();ctx.restore();}}
function paintOrder(){const items=[...state.entities,...state.pickups],background=items.filter(backgroundItem),foreground=items.filter(item=>!backgroundItem(item)),supports=state.entities.filter(e=>!backgroundItem(e)&&(e.type==='platform'||e.type==='fireEscape')&&e.y>0);return{background,foreground,supports};}
function draw(){renderQueued=false;if(!canvas.width)return;const m=metrics(),plate=drawBackground(m);drawGrid(m);ctx.fillStyle='rgba(18,28,32,.38)';ctx.fillRect(0,m.ground,m.width,m.height-m.ground);ctx.strokeStyle='rgba(255,255,255,.7)';ctx.beginPath();ctx.moveTo(0,m.ground+.5);ctx.lineTo(m.width,m.ground+.5);ctx.stroke();const layers=paintOrder();ctx.save();ctx.beginPath();ctx.rect(0,0,m.width,Math.max(0,m.ground-plate.laneClearance*m.scale));ctx.clip();for(const item of layers.background)drawItem(item,m,item.id===state.selected,plate.laneClearance);ctx.restore();for(const e of layers.supports){supportColumn(e.x+e.width*.25,e.y,m);supportColumn(e.x+e.width*.75,e.y,m);}for(const item of layers.foreground)drawItem(item,m,item.id===state.selected,plate.laneClearance);drawRuler(m);if(state.entities.some(e=>shapeFor(e)?.loop))requestAnimationFrame(scheduleDraw);}
function scheduleDraw(){if(!renderQueued){renderQueued=true;requestAnimationFrame(draw);}}
function drawRuler(m){ctx.save();ctx.fillStyle='rgba(16,25,29,.82)';ctx.fillRect(0,0,m.width,24);ctx.fillStyle='#d9d2c4';ctx.font='9px Space';const step=state.zoom<.35?500:250,start=Math.floor(state.scroll/step)*step;for(let x=start;x<state.scroll+m.width/state.zoom;x+=step){const sx=m.x(x);ctx.fillRect(sx,17,1,7);ctx.fillText(`${Math.round(x/10)}m`,sx+4,12);}ctx.restore();}
function backgroundItem(item){const sh=shapeFor(item);return!!(item.background||sh?.decorative);}
function hitTest(clientX,clientY){const rect=canvas.getBoundingClientRect(),m=metrics(),plate=plateFor(m),wx=(clientX-rect.left)/m.scale+state.scroll,wy=(m.ground-(clientY-rect.top))/m.scale;const foreground=[...state.pickups,...state.entities].filter(item=>!backgroundItem(item)).reverse(),background=[...state.entities].filter(backgroundItem).reverse();return[...foreground,...background].find(item=>{const sh=shapeFor(item);if(!sh)return false;const frame=frameFor(item,sh),placement=backgroundPlacement(item,sh,frame,m.ground/m.scale,plate.laneClearance),bounds=renderedBounds(item,sh,placement,frame);return wx>=bounds.left&&wx<=bounds.right&&wy>=bounds.bottom&&wy<=bounds.top;});}
function worldAt(clientX,clientY){const rect=canvas.getBoundingClientRect(),m=metrics();return{x:(clientX-rect.left)/m.scale+state.scroll,y:(m.ground-(clientY-rect.top))/m.scale};}

function renderPalette(filter=''){const terms=filter.trim().toLowerCase();const groups=[...GROUPS,['100 ASSET PLAYGROUND',BUILDER_CATALOG.map(entry=>entry.id)]];$('paletteList').replaceChildren(...groups.map(([label,types])=>{const matches=types.filter(type=>{const entry=BUILDER_BY_ID[type],sh=shapeForType(type);return sh&&`${type} ${sh.name} ${sh.move||''} ${sh.behavior||''} ${entry?.group||''} ${entry?.note||''}`.toLowerCase().includes(terms);});if(!matches.length)return document.createDocumentFragment();const section=document.createElement('section');section.className='palette-group';section.innerHTML=`<h2>${label}</h2>`;for(const type of matches){const entry=BUILDER_BY_ID[type],sh=shapeForType(type),button=document.createElement('button'),thumb=document.createElement('canvas'),text=document.createElement('span');button.className='palette-item';button.draggable=true;button.dataset.type=type;button.dataset.kind=entry?.kind||(PICKUPS[type]?'pickup':'entity');thumb.width=84;thumb.height=80;text.innerHTML=`<strong>${sh.name}</strong><small>${entry?.behavior||(PICKUPS[type]?'pickup':sh.move)}</small>`;button.append(thumb,text);button.addEventListener('dragstart',event=>{paletteDrag={type,kind:button.dataset.kind};event.dataTransfer.setData('application/x-sneakers-element',JSON.stringify(paletteDrag));event.dataTransfer.effectAllowed='copy';});button.addEventListener('pointerdown',()=>{paletteDrag={type,kind:button.dataset.kind};});let lastPaletteAdd=0,addFromPalette=()=>{const now=performance.now();if(now-lastPaletteAdd<50)return;lastPaletteAdd=now;add(type,button.dataset.kind,state.scroll+550,0);};button.addEventListener('click',event=>{if(event.detail===2)addFromPalette();});button.addEventListener('mousedown',event=>{if(event.detail===2)addFromPalette();});button.addEventListener('mouseup',event=>{if(event.detail===2)addFromPalette();});button.addEventListener('dblclick',addFromPalette);button.addEventListener('drag',event=>{if(event.clientX){lastPointer.x=event.clientX;lastPointer.y=event.clientY;}});button.addEventListener('dragend',event=>{if(!paletteDrag)return;const x=event.clientX||lastPointer.x,y=event.clientY||lastPointer.y,rect=canvas.getBoundingClientRect();if(x>=rect.left&&x<=rect.right&&y>=rect.top&&y<=rect.bottom)placePaletteItem({clientX:x,clientY:y,preventDefault(){},dataTransfer:null});else paletteDrag=null;});section.append(button);requestAnimationFrame(()=>{const c=thumb.getContext('2d'),base=entry?.base||type,baseShape=shapeForType(base),special=baseShape?.special;if(special){const source=URBAN_KIT[special],scale=Math.min(70/source[2],62/source[3]);kitSprite(c,special,42,70,scale,1,baseShape.artOffsetY||0);}else if(baseShape){const f=manifest.sprites[baseShape.art]?.[0];if(f){const scale=Math.min(70/f.width,62/f.height);sprite(c,baseShape.art,base==='coin'?2:0,42,70,scale);}}});}return section;}));}
function sync(){const item=selected(),sh=item&&shapeFor(item),base=item&&baseCollisionItem(item),baseShape=base&&SHAPES[base.type];$('emptyState').hidden=state.entities.length+state.pickups.length>0;$('routeName').value=state.name;$('routeMeta').textContent=`${state.entities.length+state.pickups.length} elements · ${Math.round(state.length/10)} m`;$('worldEnd').textContent=`${Math.round(state.length/10)} m`;$('emptyInspector').hidden=!!item;$('inspectorForm').hidden=!item;$('selectionKind').textContent=item?(isPickup(item)||entryFor(item)?.kind==='pickup'?'PICKUP':baseShape?.enemy?'ENEMY':'WORLD ELEMENT'):'NOTHING SELECTED';if(item){$('selectionName').textContent=sh.name;$('selectionId').textContent=item.id;$('xInput').value=Math.round(item.x);$('yInput').value=Math.round(item.y||0);$('dimensionLabel').textContent=`${Math.round(sh.width)} × ${Math.round(sh.height)}`;$('patrolFields').hidden=isPickup(item)||!baseShape?.enemy;$('patrolToggle').checked=!!item.patrol;if(item.patrol){$('patrolRange').value=Math.round((item.patrol.max-item.patrol.min)/2);$('patrolSpeed').value=Math.round(item.patrol.speed);}drawPreview(item);}checks();updateMinimap();scheduleDraw();}
function drawPreview(item){previewCtx.clearRect(0,0,preview.width,preview.height);const sh=shapeFor(item),scale=Math.min(180/sh.width,115/sh.height);if(sh.special)kitSprite(previewCtx,sh.special,preview.width/2,132,scale,1,sh.artOffsetY||0);else sprite(previewCtx,sh.art,item.type==='coin'?2:0,preview.width/2,132,scale);}
function checks(){const issues=[];const all=[...state.entities,...state.pickups];if(!all.length)issues.push(['warn','Route is empty. Add a first encounter.']);else issues.push(['ok',`${state.entities.length} world elements and ${state.pickups.length} pickups.`]);const start=state.entities.filter(e=>e.x<800&&!e.background);if(start.length)issues.push(['warn','Keep the first 80 m clear for a readable start.']);const tooHigh=all.filter(e=>(e.y||0)>520);if(tooHigh.length)issues.push(['error',`${tooHigh.length} element${tooHigh.length>1?'s are':' is'} above the playable jump range.`]);const platforms=state.entities.filter(e=>!e.background&&['platform','fireEscape'].includes(e.type));const highPlatforms=platforms.filter(e=>Math.max(...topFaces(baseCollisionItem(e)).map(face=>face.y),0)>PLATFORM_RULES.maxPlatformTop);if(highPlatforms.length)issues.push(['error',`${highPlatforms.length} platform${highPlatforms.length>1?'s are':' is'} too high for a double jump.`]);const backgroundItems=state.entities.filter(e=>e.background||shapeForType(e.type)?.decorative);const backgroundSolids=backgroundItems.filter(e=>solidBoxes(baseCollisionItem(e)).length);if(backgroundSolids.length)issues.push(['error',`${backgroundSolids.length} background element${backgroundSolids.length>1?'s have':' has'} gameplay collision.`]);const colliders=state.entities.filter(e=>!e.background&&!e.decorative&&!shapeForType(e.type)?.decorative&&solidBoxes(baseCollisionItem(e)).length);const overlaps=[];for(let i=0;i<colliders.length;i++)for(let j=i+1;j<colliders.length;j++){const a=colliders[i],b=colliders[j];if(solidBoxes(baseCollisionItem(a)).some(first=>solidBoxes(baseCollisionItem(b)).some(second=>first.x<second.x+second.w&&first.x+first.w>second.x&&first.y<second.y+second.h&&first.y+first.h>second.y)))overlaps.push([a,b]);}if(overlaps.length)issues.push(['error',`${overlaps.length} solid overlap${overlaps.length>1?'s':''}; separate the colliders before playtesting.`]);else if(all.length)issues.push(['ok','Foreground lane is reserved for solid gameplay pieces; background art is depth-separated.']);const density=[];for(let x=0;x<state.length;x+=2400){const count=backgroundItems.filter(e=>!e.backgroundGroup&&e.x>=x&&e.x<x+2400).length;if(count>3)density.push(count);}if(density.length)issues.push(['warn',`Background is dense in ${density.length} window${density.length>1?'s':''}; keep fly-bys selective.`]);if(!issues.some(i=>i[0]==='error'))issues.push(['ok','All elements are inside the playable height and double-jump ceiling.']);$('routeChecks').innerHTML=issues.map(([level,text])=>`<li class="${level}"><i></i><span>${text}</span></li>`).join('');}
function updateMinimap(){const view=canvas.getBoundingClientRect().width/state.zoom,pct=state.scroll/state.length*100,width=Math.min(100,view/state.length*100);$('minimapView').style.left=`${clamp(pct,0,100-width)}%`;$('minimapView').style.width=`${width}%`;}
function status(text){$('canvasStatus').textContent=text;$('canvasStatus').classList.remove('canvas-toast');void $('canvasStatus').offsetWidth;$('canvasStatus').classList.add('canvas-toast');}
function setZoom(next,focus=.5){const old=state.zoom,width=canvas.getBoundingClientRect().width,before=state.scroll+width*focus/old;state.zoom=clamp(next,.2,1);state.scroll=Math.max(0,before-width*focus/state.zoom);$('zoomLabel').value=`${Math.round(state.zoom*100)}%`;sync();}
function fit(){const width=canvas.getBoundingClientRect().width;state.scroll=0;state.zoom=clamp(width/Math.max(1200,state.length),.2,1);$('zoomLabel').value=`${Math.round(state.zoom*100)}%`;sync();}
function loadStage(index){checkpoint();const route=makeRoute(index);state.stage=index;state.sceneStage=index;state.name=`${LEVELS[index].name} edit`;state.entities=route.entities.map(cleanEntity).filter(Boolean);state.pickups=route.pickups.map(p=>({...cleanPickup(p),kind:'pickup'}));state.length=route.length;state.selected=null;state.scroll=0;state.zoom=.5;$('zoomLabel').value='50%';$('sceneSelect').value=state.sceneStage;loadScene();sync();status(`Loaded ${LEVELS[index].name}`);}
function loadPlayground(){checkpoint();state.stage=0;state.sceneStage=0;state.name=`Asset Playground · ${BUILDER_COUNT} ideas`;const cell=1000,start=800;state.entities=[];state.pickups=[];BUILDER_CATALOG.forEach((entry,index)=>{const x=start+index*cell,y=index%2?160:0,sh=shapeForType(entry.base);if(entry.kind==='pickup'){state.pickups.push({id:`playground:${entry.id}`,kind:'pickup',type:entry.id,x,y:Math.max(70,y+90)});}else{state.entities.push({id:`playground:${entry.id}`,type:entry.id,x,y,width:sh.width,hit:false,passed:false});}});state.length=start+BUILDER_COUNT*cell+700;state.selected=null;state.scroll=0;state.zoom=.38;$('stageSelect').value=state.stage;$('sceneSelect').value=state.sceneStage;$('zoomLabel').value='38%';loadScene();sync();status(`Loaded ${BUILDER_COUNT} asset ideas for testing`);}
function save(){try{localStorage.setItem(STORE,snapshot());state.dirty=false;status('Draft saved in this browser');}catch{status('Draft saving is unavailable in this browser');}}
function exportJSON(){const blob=new Blob([JSON.stringify(serialise(),null,2)+'\n'],{type:'application/json'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`${state.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')||'sneakers-route'}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),0);status('JSON exported');}

function dragItem(){return state.drag?.mode==='item'?[...state.entities,...state.pickups].find(item=>item.id===state.drag.id)||null:null;}
function finishDrag(){if(state.drag?.moved){state.history.push(state.drag.before);state.future=[];state.dirty=true;updateHistory();status('Moved element');}state.drag=null;canvas.classList.remove('dragging');}
canvas.addEventListener('pointerdown',event=>{try{canvas.setPointerCapture(event.pointerId);}catch{}const item=hitTest(event.clientX,event.clientY),point=worldAt(event.clientX,event.clientY),m=metrics(),plate=plateFor(m);if(item){state.selected=item.id;const sh=shapeFor(item),lift=backgroundVisualLift(item,sh,frameFor(item,sh),m.ground/m.scale,plate.laneClearance);state.drag={mode:'item',id:item.id,dx:point.x-item.x,dy:point.y-((item.y||0)+lift),before:snapshot(),moved:false};}else{state.selected=null;state.drag={mode:'pan',startX:event.clientX,scroll:state.scroll};}canvas.classList.add('dragging');sync();});
canvas.addEventListener('pointermove',event=>{if(!state.drag)return;if(event.buttons===0){finishDrag();return;}if(state.drag.mode==='pan'){state.scroll=Math.max(0,state.drag.scroll-(event.clientX-state.drag.startX)/state.zoom);updateMinimap();scheduleDraw();return;}const item=dragItem(),point=worldAt(event.clientX,event.clientY),m=metrics(),plate=plateFor(m);if(!item)return;const oldX=item.x,sh=shapeFor(item),lift=backgroundVisualLift(item,sh,frameFor(item,sh),m.ground/m.scale,plate.laneClearance);item.x=Math.max(0,snap(point.x-state.drag.dx));item.y=Math.max(0,snap(point.y-state.drag.dy-lift));if(item.patrol){const delta=item.x-oldX;item.patrol.min+=delta;item.patrol.max+=delta;}state.drag.moved=true;normalizeLength();sync();});
canvas.addEventListener('pointerup',finishDrag);canvas.addEventListener('pointercancel',finishDrag);canvas.addEventListener('lostpointercapture',finishDrag);
$('canvasWrap').addEventListener('dragover',event=>{event.preventDefault();event.dataTransfer.dropEffect='copy';$('canvasWrap').classList.add('drag-over');});
canvas.addEventListener('dragover',event=>{event.preventDefault();event.dataTransfer.dropEffect='copy';});
$('canvasWrap').addEventListener('dragleave',()=> $('canvasWrap').classList.remove('drag-over'));
document.addEventListener('pointermove',event=>{lastPointer.x=event.clientX;lastPointer.y=event.clientY;});
function placePaletteItem(event){event.preventDefault();$('canvasWrap').classList.remove('drag-over');if(!paletteDrag)return;const data=paletteDrag;try{const point=worldAt(event.clientX,event.clientY),sh=shapeForType(data.type);if(!sh)throw new Error('unknown asset');add(data.type,data.kind,data.kind==='pickup'?point.x:point.x-sh.width/2,Math.max(data.kind==='pickup'?25:0,point.y));}catch{status('That item could not be placed');}finally{paletteDrag=null;}}
$('canvasWrap').addEventListener('drop',placePaletteItem);
canvas.addEventListener('drop',placePaletteItem);
$('canvasWrap').addEventListener('pointerup',event=>{if(paletteDrag)placePaletteItem(event);});
canvas.addEventListener('wheel',event=>{event.preventDefault();if(event.ctrlKey||event.metaKey)setZoom(state.zoom*(event.deltaY>0?.9:1.1),(event.clientX-canvas.getBoundingClientRect().left)/canvas.getBoundingClientRect().width);else{state.scroll=Math.max(0,state.scroll+(event.deltaX||event.deltaY)/state.zoom);updateMinimap();scheduleDraw();}},{passive:false});
canvas.addEventListener('keydown',event=>{const item=selected();if(['Delete','Backspace'].includes(event.key)&&item){event.preventDefault();removeSelected();return;}if(!item||!event.key.startsWith('Arrow'))return;event.preventDefault();checkpoint();const step=event.shiftKey?10:1,dx=event.key==='ArrowLeft'?-step:event.key==='ArrowRight'?step:0,dy=event.key==='ArrowDown'?-step:event.key==='ArrowUp'?step:0;item.x=Math.max(0,item.x+dx);item.y=Math.max(0,(item.y||0)+dy);if(item.patrol){item.patrol.min+=dx;item.patrol.max+=dx;}normalizeLength();sync();});
document.addEventListener('keydown',event=>{if(!(event.metaKey||event.ctrlKey))return;if(event.key.toLowerCase()==='z'){event.preventDefault();event.shiftKey?redo():undo();}if(event.key.toLowerCase()==='d'&&selected()){event.preventDefault();duplicateSelected();}if(event.key.toLowerCase()==='s'){event.preventDefault();save();}});

for(let i=0;i<LEVELS.length;i++){const label=`${String(i+1).padStart(2,'0')} · ${LEVELS[i].name}`;$('stageSelect').add(new Option(label,i));$('sceneSelect').add(new Option(label,i));}
$('stageSelect').addEventListener('change',event=>loadStage(Number(event.target.value)));
$('sceneSelect').addEventListener('change',event=>{state.sceneStage=clamp(Number(event.target.value)||0,0,LEVELS.length-1);checkpoint();loadScene();sync();status(`Background: ${LEVELS[state.sceneStage].name}`);});
$('paletteSearch').addEventListener('input',event=>renderPalette(event.target.value));
$('routeName').addEventListener('change',event=>{checkpoint();state.name=event.target.value.trim()||'Untitled route';sync();});
$('gridSelect').addEventListener('change',event=>{state.grid=Number(event.target.value);scheduleDraw();});
$('hitboxToggle').addEventListener('change',event=>{state.showBoxes=event.target.checked;scheduleDraw();});
$('undoButton').addEventListener('click',undo);$('redoButton').addEventListener('click',redo);$('deleteButton').addEventListener('click',removeSelected);$('duplicateButton').addEventListener('click',duplicateSelected);$('saveButton').addEventListener('click',save);$('exportButton').addEventListener('click',exportJSON);$('importButton').addEventListener('click',()=>$('fileInput').click());
$('playgroundButton').addEventListener('click',loadPlayground);
$('zoomOut').addEventListener('click',()=>setZoom(state.zoom-.1));$('zoomIn').addEventListener('click',()=>setZoom(state.zoom+.1));$('fitButton').addEventListener('click',fit);
$('xInput').addEventListener('change',event=>changePosition('x',event.target.value));$('yInput').addEventListener('change',event=>changePosition('y',event.target.value));
function changePosition(axis,value){const item=selected();if(!item)return;checkpoint();const before=item.x;item[axis]=Math.max(0,Number(value)||0);if(axis==='x'&&item.patrol){const delta=item.x-before;item.patrol.min+=delta;item.patrol.max+=delta;}normalizeLength();sync();}
$('patrolToggle').addEventListener('change',event=>{const item=selected();if(!item)return;checkpoint();if(event.target.checked){const range=Number($('patrolRange').value);item.patrol={min:item.x-range,max:item.x+range,speed:Number($('patrolSpeed').value)};item.direction=-1;}else delete item.patrol;sync();});
for(const id of ['patrolRange','patrolSpeed'])$(id).addEventListener('change',()=>{const item=selected();if(!item?.patrol)return;checkpoint();const range=Number($('patrolRange').value);item.patrol={min:item.x-range,max:item.x+range,speed:Number($('patrolSpeed').value)};sync();});
$('fileInput').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{checkpoint();restore(JSON.parse(await file.text()));status(`Imported ${file.name}`);}catch{state.history.pop();status('Import failed: choose a valid route JSON file');}event.target.value='';});
window.addEventListener('beforeunload',event=>{if(state.dirty){event.preventDefault();event.returnValue='';}});new ResizeObserver(resize).observe($('canvasWrap'));

await loadAssets();renderPalette();let stored=null;try{stored=localStorage.getItem(STORE);}catch{}if(stored){try{restore(stored);status('Restored saved draft');}catch{loadStage(0);}}else loadStage(0);state.history=[];state.future=[];state.dirty=false;updateHistory();
if(new URLSearchParams(location.search).has('test'))window.__EDITOR_TEST__={state:()=>structuredClone(serialise()),add,select:id=>{state.selected=id;sync();},undo,redo,loadStage,loadPlayground,setBackground:index=>{$('sceneSelect').value=index;state.sceneStage=clamp(Number(index)||0,0,LEVELS.length-1);loadScene();sync();},scrollTo:value=>{state.scroll=Math.max(0,Number(value)||0);sync();},save,extent:()=>extent(),catalog:()=>structuredClone(BUILDER_CATALOG),placement:(item,worldHeight)=>{const m=metrics(),plate=plateFor(m);return structuredClone(backgroundPlacement(item,shapeFor(item),frameFor(item,shapeFor(item)),worldHeight??m.ground/m.scale,plate.laneClearance));},bounds:item=>{const m=metrics(),plate=plateFor(m),sh=shapeFor(item),frame=frameFor(item,sh),placement=backgroundPlacement(item,sh,frame,m.ground/m.scale,plate.laneClearance);return structuredClone(renderedBounds(item,sh,placement,frame));},view:()=>{const m=metrics(),plate=plateFor(m);return{scale:m.scale,ground:m.ground,scroll:state.scroll,laneClearance:plate.laneClearance};},paintOrder:()=>Object.fromEntries(Object.entries(paintOrder()).map(([layer,items])=>[layer,items.map(item=>item.id)]))};
